### ISSUE TITLE
ImportError: No module named pwn

### ISSUE THREAD

**Issue by code-scan** [YSc21/aegg#1]
> > > from aegg import AEGG
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "aegg.py", line 1, in <module>
> > >     from analyzer import Analyzer
> > >   File "analyzer.py", line 3, in <module>
> > >     from pwn import *
> > > ImportError: No module named pwn

**Comment by code-scan** [comment]
pip install pwn is ok
